# https://docs.docker.com/compose/extends/
# Specific dev config

version: '3.6'
services:
  django:
    ports:
      - "8000:8000"
    image: {{ cookiecutter.project_slug }}_dev_django
    build:
      args:
        DJANGO_ENV: dev
    command: /app/docker/django/start_dev
    entrypoint: /app/docker/django/entrypoint
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    image: {{ cookiecutter.project_slug }}_dev_node
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
