#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate --noinput
python manage.py collectstatic --noinput
/usr/local/bin/gunicorn {{cookiecutter.project_slug}}.wsgi --bind 0.0.0.0:8000
